# ---
- name: Removing default nginx.conf.default
  file: path="{{ nginx_install_path }}/conf/nginx.conf.default" state="absent"
  become: yes
  become_user: root
  
- name: Sending our default app passenger config
  template: src=./../templates/nginx_application.conf dest="{{ nginx_install_path }}/conf/conf.d/{{ app_name }}.conf"
  become: yes
  become_user: root

- name: git clone from repo
  git: repo={{ source_code_url }} dest="{{ app_path }}/{{ app_name }}" clone=yes version={{ git_branch }}

- name: Sending the Database yml over
  template: src=./../templates/application_database.yml dest="{{ app_path }}/{{ app_name }}/config/database.yml"

- name: Send Gemrc to deployer home directory
  template: src=./../templates/gemrc dest="~/.gemrc"

- name: install epel-release
  yum: name=epel-release state=present
  become: yes
  become_user: root

- name: Install Node JS for Rails
  yum: name=nodejs state=present
  become: yes
  become_user: root

- name: Install bundler gem
  shell: 'source ~/.bash_profile && gem install bundler'

- name: Run bundle install
  shell: source ~/.bash_profile && bundle install --without development test chdir="{{ app_path }}/{{ app_name }}"

- name: Run rake db:migrate
  shell: source ~/.bash_profile && RAILS_ENV=production rake db:create db:migrate chdir="{{ app_path }}/{{ app_name }}"

- name: Precompile the assets
  shell: source ~/.bash_profile && RAILS_ENV=production rake assets:precompile chdir="{{ app_path }}/{{ app_name }}"

- name: start nginx 
  shell: sudo ./nginx restart chdir=/etc/init.d
