---
- name: get user home PATH
  command: echo $HOME
  register: home_path

- name: get current ruby version
  shell: "PATH={{ home_path.stdout }}/bin ruby -v"
  register: current_ruby_version
  ignore_errors: true

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present
  become: yes
  become_user: root
  when: current_ruby_version.stdout == ''

- name: install ruby dependencies
  action: yum name={{ item }} state=present
  with_items:
    - zlib
    - zlib-devel
    - openssl-devel
  become: yes
  become_user: root    
  when: current_ruby_version.stdout == ''

- name: make source directory in user home
  file: path="{{ home_path.stdout }}/src" state=directory mode=0755 recurse=yes

- name: download Ruby Source
  get_url:
    dest: "{{ home_path.stdout }}/src"
    url: http://ring.shibaura-it.ac.jp/archives/lang/ruby/ruby-{{ ruby_version_to_install }}.tar.gz
    sha256sum: "{{ ruby_checksum_sha256 }}"
    force: no
  when: current_ruby_version.stdout == ''

- name: unpack ruby
  unarchive:
    copy: no
    dest: "{{ home_path.stdout }}/src"
    creates: "{{ home_path.stdout }}/src/ruby-{{ ruby_version_to_install }}"
    src: "{{ home_path.stdout }}/src/ruby-{{ ruby_version_to_install }}.tar.gz"
  when: current_ruby_version.stdout == ''

- name: configure ruby
  command: ./configure --prefix={{ home_path.stdout }}
  args:
    chdir: "{{ home_path.stdout }}/src/ruby-{{ ruby_version_to_install }}"
    creates: Makefile
  when: current_ruby_version.stdout == ''

- name: compile ruby
  command: make
  args:
    chdir: "{{ home_path.stdout }}/src/ruby-{{ ruby_version_to_install }}"
    creates: ruby
  when: current_ruby_version.stdout == ''

- name: install ruby
  command: make install
  args:
    chdir: "{{ home_path.stdout }}/src/ruby-{{ ruby_version_to_install }}"
  when: current_ruby_version.stdout == ''

- name: update ruby gems
  shell: "source ~/.bash_profile && gem update --system {{ ruby_gems_version }}" 
